[package]
name = "graph"
version = "1.0.0-alpha"
authors = ["Gauvain Devillez <gauvain.devillez@umons.ac.be>"]
build = "build.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
bit-vec = "0.4"
libc = "0.2"
